#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd & 

bspc monitor -d 1 2 3 4 5 6 &

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config top_padding        6
bspc config bottom_padding     36
bspc config left_padding       5
bspc config right_padding      5
bspc config border_width       2
bspc config window_gap         14
bspc config border_radius      10


xsetroot -cursor_name left_ptr &

${HOME}/.fehbg
compton &
polybar -c ~/.config/polybar/config example & 

sleep 2 && plank 